### ISSUE TITLE
Sorting collection data

### ISSUE THREAD

**Issue by Mattia541993** [strapi/jekyll-strapi#15]
Hi! Is there a way to sort the collection data returned from strapi? From the API I saw it's possible to define additional query parameters.

Thank you

**Comment by bluszcz** [comment]
I think that this:

https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/sort-pagination.html#sorting

combine with ability to customize requests parameters:

https://github.com/strapi-community/jekyll-strapi/blob/master/README.md#request-parameters

shall allow you to accomplish the task.
