### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by Mattia541993** [strapi/jekyll-strapi#16]
Hi! Is there a way to authenticate the network request made from `jekyll-strapi` plugin? I saw from the strapi website that there are various ways to [set header with different authentication methods](https://strapi.io/documentation/developer-docs/latest/development/plugins/users-permissions.html#token-usage). I'd like to know if would be possible to have such like a token to put in the `_config.yml` under the `strapi` key.
Thank you

**Comment by bluszcz** [comment]
Hello @Mattia541993 - there is a PR with authentication working.

**Comment by bluszcz** [comment]
Authentication have been provided with the new release plugin for Strapi 4.
