### ISSUE TITLE
Strapi v4 compatibility

### ISSUE THREAD

**Issue by prestigelinks** [strapi/jekyll-strapi#20]
This plugin does not seem to work with Strapi v4, at least using the tutorial here:

https://docs.strapi.io/developer-docs/latest/developer-resources/content-api/integrations/jekyll.html#get-request-your-collection-type

I think this may be because the format of the API responses has changed.

**Comment by paulkitt** [comment]
Anybody working on this or is this project just dead?

**Comment by bluszcz** [comment]
Hello @paulkitt, project is not dead and currently is being maintained. We have just released update for the version 4.

**Comment by paulkitt** [comment]
Amazing! Thank you for your effort
