### ISSUE TITLE
Strapi favicon loading behind custom favicon

### ISSUE THREAD

**Issue by oDinZu** [strapi/jekyll-strapi#28]
`ffmpeg -i input_video_file.mp4 output.gif`

![strapi-favicon-v4 1 11-2022-7-5](https://user-images.githubusercontent.com/18726788/177385392-e46bf158-e488-4f2e-914f-a8a86ed53b36.gif)

**strapi version: v4.1.11**

**Comment by oDinZu** [comment]
Ok, thanks to Strapi amazing :1st_place_medal: support + Derrick super awesome sauce. 

All you need to do is replace the favicon.ico in the root of the project, then rebuild the app.

We have figured out why this is happening. I added images to: `./strapi-app/ src/admin/extensions`
then, added this to my: ./strapi-app/src/admin/app.js
```
...
        //replace favicon with custom icon
        head: {
            favicon: favicon,
        },
...
```

The instructions here on Strapi docs entails us to replace the favicon without replacing root favicon.ico
https://docs.strapi.io/developer-docs/latest/development/admin-customization.html#configuration-options

**Comment by derrickmehaffy** [comment]
> Ok, thanks to Strapi amazing 1st_place_medal support + Derrick super awesome sauce.
> 
> All you need to do is replace the favicon.ico in the root of the project, then rebuild the app.
> 
> We have figured out why this is happening. I added images to: `./strapi-app/ src/admin/extensions` then, added this to my: ./strapi-app/src/admin/app.js
> 
> ```
> ...
>         //replace favicon with custom icon
>         head: {
>             favicon: favicon,
>         },
> ...
> ```
> 
> The instructions here on Strapi docs entails us to replace the favicon without replacing root favicon.ico https://docs.strapi.io/developer-docs/latest/development/admin-customization.html#configuration-options

Can you open an issue on our documentation repo about this one? Because those docs are absolutely wrong, sorry about that!
