### ISSUE TITLE
Failed to open TCP connection

### ISSUE THREAD

**Issue by YannickDurden** [strapi/jekyll-strapi#34]
Hi,

following the instructions here : [Getting Started with Jekyll]( https://docs.strapi.io/developer-docs/latest/developer-resources/content-api/integrations/jekyll.html#create-a-jekyll-app)

I changed my Gemfile like this:

````
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-strapi-4"
end
````

But when I start the jekyll server, this message appear in the terminal:

`Failed to open TCP connection to http://localhost:1337/api/categories:80 (no implicit conversion of URI::HTTP into String) (TypeError)`

Is it a miss configuration?

_Note: I've got the latest version of Strapi_

**Comment by bluszcz** [comment]
Hello, thank you for your bug report.

There are two things - I think that documentation which you refer to is for the old version of the plugin. Second - can you share start logs from your running Strapi instances? to see which port its running.

There is official README here: https://github.com/strapi-community/jekyll-strapi/blob/master/README.md and an article: https://dev.to/bluszcz/static-site-generator-with-strapi-4-and-jekyll-5afp - maybe it will help.

**Comment by YannickDurden** [comment]
Hi,

thanks for helping me. Below you will find a screenshot. In the left panel, it's jekyll. In the right panel it's strapi.

I tried the tutorial, the only difference it's the gem version for jekyll strapi. I'm running jekyll with ruby v2.7 so the gem is the 1.0.9. 

<img width="1110" alt="jekyll strapi" src="https://user-images.githubusercontent.com/25035952/199483923-8fb79a6d-8215-4e77-b7f9-97d832492ae8.png">

**Comment by bluszcz** [comment]
Thank you - is the traceback on the left complete? If not please share whole.

**Comment by YannickDurden** [comment]
I guess it was fixed between 1.0.9 and 1.0.12 because I updated my ruby version to 3.0.0 and I added the gem 1.0.12, without changing my configuration, and it's working. 

Sadly, I cannot reproduce the bug unless I downgrade my ruby version (or maybe using 1.0.9, who knows)

**Comment by bluszcz** [comment]
Plugin works only with Ruby 3 I believe

**Comment by YannickDurden** [comment]
That's why! 

Just a last question, but it should be a new case: 

If a call "/posts" , I don't have image associate to a single post. If we call /posts?populate=*, I have my image post cover. Is there a configuration to do it? For a single post, like /posts/1 it's OK but not for each posts.

Thank again ✌️

**Comment by bluszcz** [comment]
Yes, there is a configuration for it, check parameter `populate` :)
